/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emlaktakipprojesi;

import Database.Veritabani;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author speakingJoy
 */
public class Emlak_Ekle extends javax.swing.JFrame {

    /**
     * Creates new form Müsteri_Eklemee
     */
    private EmlakTakipProjesi gelen;
    Veritabani database ;
    public Emlak_Ekle(EmlakTakipProjesi etp) {
        this.gelen=etp;
        database=new Veritabani();
        initComponents();
        MusteriCek();
        
    }

    private Emlak_Ekle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbemlaktur = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfiyat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtadres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbmusteri = new javax.swing.JComboBox();
        jbEmlakKaydet = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtmetre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtCephe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtOda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtBanyo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtTuvalet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtBlndgKat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jcbemlaktur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbemlaktur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kiralık Arsa", "Satılık Arsa", "Kiralık Ev", "Satılık Ev", "Kiralık İşyeri", "Satılık İşyeri", "Günlük Daire", " " }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMLAK TÜRÜ");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FİYAT");

        jtfiyat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtfiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfiyatActionPerformed(evt);
            }
        });
        jtfiyat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfiyatKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADRES");

        jtadres.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtadresActionPerformed(evt);
            }
        });
        jtadres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtadresKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMLAK SAHİBİ");

        jcbmusteri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbmusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmusteriActionPerformed(evt);
            }
        });

        jbEmlakKaydet.setBackground(new java.awt.Color(255, 255, 255));
        jbEmlakKaydet.setText("KAYDET");
        jbEmlakKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmlakKaydetActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("metre2");

        jtmetre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtmetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtmetreActionPerformed(evt);
            }
        });
        jtmetre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtmetreKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cephesi");

        jtCephe.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtCephe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCepheActionPerformed(evt);
            }
        });
        jtCephe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCepheKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Oda Sayısı");

        jtOda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtOda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtOdaActionPerformed(evt);
            }
        });
        jtOda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtOdaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Banyo Sayısı");

        jtBanyo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtBanyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBanyoActionPerformed(evt);
            }
        });
        jtBanyo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtBanyoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tuvalet Sayısı");

        jtTuvalet.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtTuvalet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTuvaletActionPerformed(evt);
            }
        });
        jtTuvalet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTuvaletKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bulunduğu Kat");

        jtBlndgKat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtBlndgKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBlndgKatActionPerformed(evt);
            }
        });
        jtBlndgKat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtBlndgKatKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtadres)
                            .addComponent(jcbmusteri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfiyat)
                            .addComponent(jcbemlaktur, 0, 669, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbEmlakKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtBanyo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jtmetre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtTuvalet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtCephe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtOda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtBlndgKat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbemlaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtadres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbmusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtCephe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtOda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtmetre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBlndgKat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBanyo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTuvalet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEmlakKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfiyatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfiyatActionPerformed

    private void jtfiyatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfiyatKeyTyped
        char c = evt.getKeyChar();

        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE )) {

            JOptionPane.showMessageDialog(rootPane, "Lütfen Rakam Giriniz!!!");
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfiyatKeyTyped

    private void jtadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtadresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtadresActionPerformed

    private void jtadresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtadresKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtadresKeyTyped

    private void jbEmlakKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmlakKaydetActionPerformed
            // TODO add your handling code here:
            String emlak_turu = (String)jcbemlaktur.getSelectedItem();
            String fiyat = jtfiyat.getText();
            String adres = jtadres.getText();
            String sahib=(String)jcbmusteri.getSelectedItem();
            String metre=jtmetre.getText();
            String cephe=jtCephe.getText();
            String odaSayisi=jtOda.getText();
            String banyoSayisi=jtBanyo.getText();
            String tuvaletSayisi=jtTuvalet.getText();
            String bulunduguKat=jtBlndgKat.getText();
            database.EmlakEkle(emlak_turu, fiyat, adres, sahib,metre,cephe,odaSayisi,banyoSayisi,tuvaletSayisi,bulunduguKat);
            
        
    }//GEN-LAST:event_jbEmlakKaydetActionPerformed

    private void jcbmusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmusteriActionPerformed
        
    }//GEN-LAST:event_jcbmusteriActionPerformed

    private void jtmetreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtmetreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtmetreActionPerformed

    private void jtmetreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtmetreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtmetreKeyTyped

    private void jtCepheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCepheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCepheActionPerformed

    private void jtCepheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCepheKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCepheKeyTyped

    private void jtOdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtOdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtOdaActionPerformed

    private void jtOdaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtOdaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtOdaKeyTyped

    private void jtBanyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBanyoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBanyoActionPerformed

    private void jtBanyoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBanyoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBanyoKeyTyped

    private void jtTuvaletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTuvaletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTuvaletActionPerformed

    private void jtTuvaletKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTuvaletKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTuvaletKeyTyped

    private void jtBlndgKatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBlndgKatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBlndgKatActionPerformed

    private void jtBlndgKatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBlndgKatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBlndgKatKeyTyped
    public void MusteriCek(){
        int i=0;
        String diziMusteri[][]=database.MusteriCek();
        jcbmusteri.addItem(diziMusteri[i][0]+" "+diziMusteri[i][1]);
        jcbmusteri.addItem(diziMusteri[i+1][0]+" "+diziMusteri[i+1][1]);
        jcbmusteri.addItem(diziMusteri[i+2][0]+" "+diziMusteri[i+2][1]);
        jcbmusteri.addItem(diziMusteri[i+3][0]+" "+diziMusteri[i+3][1]);
        jcbmusteri.addItem(diziMusteri[i+4][0]+" "+diziMusteri[i+4][1]);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emlak_Ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emlak_Ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emlak_Ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emlak_Ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emlak_Ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbEmlakKaydet;
    private javax.swing.JComboBox jcbemlaktur;
    private javax.swing.JComboBox jcbmusteri;
    private javax.swing.JTextField jtBanyo;
    private javax.swing.JTextField jtBlndgKat;
    private javax.swing.JTextField jtCephe;
    private javax.swing.JTextField jtOda;
    private javax.swing.JTextField jtTuvalet;
    private javax.swing.JTextField jtadres;
    private javax.swing.JTextField jtfiyat;
    private javax.swing.JTextField jtmetre;
    // End of variables declaration//GEN-END:variables
}
